In [ ]:
import tensorflow as tf
import numpy as np

### Performing mathematical operations on tensor

### matmul() operation

In [ ]:
# matmul() operation on a 2D tensor
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
c = tf.matmul(a, b)
print(c)  

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [ ]:
# matmul() operation on a 3D tensor
d = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
e = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
f = tf.matmul(d,e)
print(f)

tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)


### add(), subtract() operations
#### Both input and output can have a range between (-infinity , infinity). If one of the inputs (x or y) is a tensor and the other is a non-tensor, the non-tensor input will adopt the data type of the tensor input. This will cause unwanted overflow or underflow conversion.

In [ ]:
x = [1, 2, 3, 4, 5]
y = 1
print (tf.subtract(x,y))
print (tf.add(x,y))

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [ ]:
# Binary operator can be used
a = tf.convert_to_tensor([1, 2, 3, 4, 5])
b = tf.convert_to_tensor(1)
print(a - b)
print(a + b)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [ ]:
x = np.ones(6).reshape(2, 3, 1)
y = np.ones(6).reshape(2, 1, 3)
print(x)
print(y)
print(tf.subtract(x, y))
print (tf.add(x,y))

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float64)
tf.Tensor(
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]], shape=(2, 3, 3), dtype=float64)


### Transpose Operation

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
# If x is complex, setting "conjugate=True" gives the conjugate transpose.
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
tf.transpose(x, conjugate=True)

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

In [ ]:
# tf.transpose will default to perm=[2,1,0]
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
tf.transpose(x, perm=[0, 2, 1])

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]], dtype=int32)>

### Perform mathematical computation on tensor through constant, variable & placeholder methods.

In [ ]:
# Constant Method
x = tf.constant([2,3])
y = tf.constant([3,4])
print (tf.add(x,y))
print (tf.subtract(x,y))

tf.Tensor([5 7], shape=(2,), dtype=int32)
tf.Tensor([-1 -1], shape=(2,), dtype=int32)


In [ ]:
# Variable Method
t1 = tf.Variable([3,4])
print(t1)

t1.assign([4,5])
print(t1)

print(t1.assign_add([2,2]))
print(t1.assign_sub([2,1]))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([6, 7], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


### Creating a dataset

In [ ]:
#dataset creation
dataset1 = tf.data.Dataset.from_tensors(tf.range(1, 15)) #using from_tensor library to create a dataset of an array from 0 to 15
print(dataset1)

<TensorDataset element_spec=TensorSpec(shape=(14,), dtype=tf.int32, name=None)>


In [ ]:
# Using tensor_slice method
dataset2 = tf.data.Dataset.from_tensor_slices(tf.range(10, 15))
print(dataset2)

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>


In [ ]:
# Using generator method
def generator(sequence_type):
    if sequence_type == 1:
        for i in range(5):
            yield 10 + i
    elif sequence_type == 2:
        for i in range(5):
            yield (3, 2 * i)
dataset3 = tf.data.Dataset.from_generator(generator, (tf.int32), args = ([1]))

print(dataset3)

Instructions for updating:
Use output_signature instead


<FlatMapDataset element_spec=TensorSpec(shape=<unknown>, dtype=tf.int32, name=None)>


### Apply different transformations techniques(as_numpy_iterator, apply, batch,cardinality, etc.) to a prepared dataset.

In [ ]:
dataset1 = dataset1.batch(3)
print(dataset1)

<BatchDataset element_spec=TensorSpec(shape=(None, 14), dtype=tf.int32, name=None)>
