In [ ]:
import tensorflow as tf
import numpy as np

### Tensors are nothing but multidimensional arrays with a uniform type called a dtype.
### Creating 1-D, 2-D,3-D & an n-dimensional tensors

In [ ]:
tf_1 = tf.constant(4)
print(tf_1)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tf_2 = tf.constant([2.0,3.0,4.0])
print(tf_2)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
tf_3 = tf.constant( [ [1, 2],[3, 4],[5, 6] ] , dtype = tf.float16 ) 
print(tf_3)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
# There can be arbitrary number of axes which are also called as dimensions
tf_4 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(tf_4)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


## Rank of the tensors

In [ ]:
print (tf.rank(tf_1) )
# This a rank-0 tensor which is also called as a scalar. It contains only a single value and has no axes.

tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
print ( tf.rank(tf_2) )
# This is a rank-1 tensor which is also called a vector. It contains only 1 axes. It basically contains a list of values.

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print ( tf.rank(tf_3) )
# This is a rank-2 tensor which is also called as a matrix. This tensor contains 2 axes.

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
print ( tf.rank(tf_4) )
# A tensor can be having more axes. The above example tf_4 is a matrix with 3 axes.

tf.Tensor(3, shape=(), dtype=int32)


### Using different methods like zeros(),ones(),fill() to create a tensor

In [ ]:
# Using zeros() method
tf_zeros_1 = tf.zeros( [3] , tf.float16 )
tf_zeros_2 = tf.zeros( [3, 4] , tf.int32)
tf_zeros_3 = tf.zeros( [2,5,10] , tf.int16 )
print(tf_zeros_1)
print(tf_zeros_2)
print(tf_zeros_3)
# We can even mention the dtype we want to get. Example :- tf.int32

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float16)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]], shape=(2, 5, 10), dtype=int16)


In [ ]:
# Using ones() method
tf_ones_1 = tf.ones( [5] , tf.float16 )
tf_ones_2 = tf.ones( [2, 3] , tf.int32)
tf_ones_3 = tf.ones( [2,4,6] , tf.int16 )
print(tf_ones_1)
print(tf_ones_2)
print(tf_ones_3)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float16)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]], shape=(2, 4, 6), dtype=int16)


In [ ]:
# Using fill() method - tf.fill( dims , value , name = None )
tf_fill_1 = tf.fill( [3] , 10 , tf.float16 )
tf_fill_2 = tf.fill( [3, 4] , 9 , tf.int32)
tf_fill_3 = tf.fill( [2,5,4] , 2 , tf.int16 )
print(tf_fill_1)
print(tf_fill_2)
print(tf_fill_3)
# We can even mention the dtype we want to get. Example :- tf.int32

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]], shape=(2, 5, 4), dtype=int32)


### Finding shape of the tensor using tensor flow library

In [ ]:
print(tf.shape(tf_1))
print(tf.shape(tf_2))
print(tf.shape(tf_3))
print(tf.shape(tf_4))

tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor([3 2 5], shape=(3,), dtype=int32)


In [ ]:
print(tf.shape(tf_zeros_1))
print(tf.shape(tf_zeros_2))
print(tf.shape(tf_zeros_3))

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([ 2  5 10], shape=(3,), dtype=int32)


In [ ]:
print(tf.shape(tf_ones_1))
print(tf.shape(tf_ones_2))
print(tf.shape(tf_ones_3))

tf.Tensor([5], shape=(1,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
print(tf.shape(tf_fill_1))
print(tf.shape(tf_fill_2))
print(tf.shape(tf_fill_3))

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([2 5 4], shape=(3,), dtype=int32)


### Reshaping the tensor

In [ ]:
tf_3_reshape = tf.reshape(tf_3, [6,1])
tf_3_reshape

<tf.Tensor: shape=(6, 1), dtype=float16, numpy=
array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]], dtype=float16)>

In [ ]:
tf_zeros_2_reshape = tf.reshape(tf_zeros_2, [12,1])
tf_zeros_2_reshape

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32)>

In [ ]:
tf_ones_2_reshape = tf.reshape(tf_ones_2, [3,2])
tf_ones_2_reshape

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

### Performing slicing on tensors

In [ ]:
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
print(t1[1:4])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
t2 = tf.constant([[0, 1, 2, 3, 4],
                  [5, 6, 7, 8, 9],
                  [10, 11, 12, 13, 14],
                  [15, 16, 17, 18, 19]])

print(t2[:-2, 1:3])

tf.Tensor(
[[1 2]
 [6 7]], shape=(2, 2), dtype=int32)
